StackStorm/puppet-st2

.gitignore, Gemfile.lock, README.md, manifests/dependencies.pp, manifests/dependencies/install.pp, manifests/init.pp, manifests/notices.pp, manifests/package/install.pp, manifests/params.pp, manifests/profile/client.pp, manifests/profile/fullinstall.pp, manifests/profile/mistral.pp, manifests/profile/mongodb.pp, manifests/profile/nodejs.pp, manifests/profile/python.pp, manifests/profile/rabbitmq.pp, manifests/profile/server.pp, manifests/profile/web.pp, manifests/stanley.pp, manifests/user.pp, metadata.json
This PR contains documentation and other metadata used to publish this module on the Puppet Forge.
=> Preparation for Forge

manifests/init.pp, manifests/profile/mistral.pp, manifests/profile/server.pp
=> Any other fixes

manifests/init.pp, manifests/params.pp, metadata.json
PR adds the necessary bits to support release `v0.7`
=> Bump module to 0.7

manifests/init.pp, manifests/profile/server.pp, metadata.json
This PR allows the ability to enable or disable `st2auth`. Disabled by default while under development.
=> Toggle st2auth

manifests/init.pp, manifests/profile/client.pp, metadata.json
This PR adds support to set the CLI RC settings, enabling things like endpoint configuration and authentication.
=> CLI RC Configuration

manifests/user.pp
Part of https://github.com/StackStorm/st2/pull/1648 (see that PR for context and details).
=> Include SETENV sudoers option for the system user

files/etc/init/mistral.conf, files/etc/systemd/system/mistral.service
This PR adds trace commands to the mistral service. 
/cc https://github.com/StackStorm/st2/pull/908
=> adding mistral trace logging config

lib/puppet/parser/functions/st2_latest_stable.rb, lib/puppet/parser/functions/st2_latest_unstable.rb
A very basic and rudimentary way to grab latest version of StackStorm via Download servers.
It's a bit of a mess, and it will get cleaned up.
=> Latest Version Updates

.gitignore, .travis.yml, Gemfile, Gemfile.lock, README.md, script/cibuild, spec/classes/init_spec.rb
Initial scaffolding for Travis CI build matrix.
=> travis ci build matrix

manifests/init.pp, manifests/profile/mistral.pp
Bumps Mistral to the latest version, and avoids a nasty bug.
/cc @m4dcoder
=> bumping mistral version and fixing bug

manifests/init.pp, manifests/profile/client.pp, manifests/profile/server.pp
This PR updates the logic necessary to properly auto-update when requested.
Also bumps the module default to 0.12.2
=> adding auto-update data

CHANGELOG.md, manifests/user.pp, metadata.json
This PR stops adjusting the UID for the Stanley user.
=> fixing stanley user UID

CHANGELOG.md, manifests/init.pp, manifests/package/install.pp, manifests/package/redhat.pp, manifests/params.pp, manifests/profile/client.pp, manifests/profile/facter.pp, manifests/profile/fullinstall.pp, manifests/profile/mistral.pp, manifests/profile/mongodb.pp, manifests/profile/python.pp, manifests/profile/rabbitmq.pp, manifests/profile/repos.pp, manifests/profile/server.pp, metadata.json, templates/etc/init.d/mistral.erb
WIP PR for adding support for RHEL 6 & 7.
=> RFR: RHEL Support

CHANGELOG.md, manifests/init.pp, manifests/profile/web.pp, templates/opt/st2web/config.js.erb
This PR adds a toggle that allows configuration of the WebUI to point to StackStorm Flow.
=> Adding flow config to WebUI profile

CHANGELOG.md, manifests/package/debian.pp, manifests/profile/server.pp, metadata.json
This commit updates the service class for StackStorm server
to restart when new packages are installed.
=> Restart services on init script or package action

Gemfile, Gemfile.lock, Rakefile
This PR allows publishing of the Puppet module via the CLI with aid from `puppet-blacksmith`
=> Adding puppet-blacksmith to build

CHANGELOG.md, manifests/profile/server.pp, metadata.json
This PR ensures that services for StackStorm are appropriately updated on configuration change.
=> refreshing services on ini update

.gitignore, manifests/helper/service_manager.pp, manifests/helper/systemd.pp, manifests/params.pp
Regardless of how this defined type is called, it should be smart enough to figure out the state of the world.
=> Consistent map list

files/etc/init.d/st2actionrunner, files/etc/init.d/st2api, files/etc/init.d/st2auth, files/etc/init.d/st2notifier, files/etc/init.d/st2resultstracker, files/etc/init.d/st2rulesengine, files/etc/init.d/st2sensorcontainer, files/etc/init.d/st2web, manifests/helper/service_manager.pp, manifests/params.pp, manifests/profile/mistral.pp, manifests/profile/server.pp
This PR adds init scripts for StackStorm into the right places for SysV systems (RHEL 6 and others)
=> System V init scripts

CHANGELOG.md, metadata.json
=> 0.9.16 release

manifests/auth/mongodb.pp, manifests/auth/proxy.pp, manifests/auth/standalone.pp, manifests/helper/actionrunner_upstart.pp, manifests/helper/auth_manager.pp, manifests/helper/service_manager.pp, manifests/profile/mistral.pp, manifests/profile/server.pp, metadata.json
Refresh is not properly propagating, so trying to revert to every resource to narrow down
=> adding tag to all resources

CHANGELOG.md, manifests/helper/auth_manager.pp, manifests/init.pp, manifests/kv.pp, manifests/pack.pp, manifests/profile/server.pp, metadata.json
This PR contains fixes for Puppet-st2 as found during testing.
=> [WIP] Module cleanup

CHANGELOG.md, manifests/auth/pam.pp, manifests/init.pp, manifests/params.pp, manifests/profile/facter.pp, manifests/profile/fullinstall.pp, manifests/profile/server.pp, metadata.json
This PR removes some issues with dependency cycles using the `fullinstall` profile.
Also bumps to latest ST2 Version
=> Module Cleanup

CHANGELOG.md, manifests/pack.pp, metadata.json
=> Packs directory should be set sticky bit

CHANGELOG.md, manifests/auth/pam.pp, manifests/init.pp, manifests/package/debian.pp, manifests/package/redhat.pp, manifests/params.pp, manifests/profile/web.pp, metadata.json
This PR adds support for downloading packages from different locations for CI purposes.
=> Parameterize download server URL

metadata.json
This PR updates the module to 0.11.2
/cc @enykeev
=> Bump module to 0.11.2

manifests/init.pp, metadata.json
This PR updates the default version to 1.2.0
=> Bump default version to 1.2.0

manifests/package/debian.pp
See https://github.com/StackStorm/puppet-st2/pull/131
=> Change GPG fingerprint for bintray to right one

manifests/package/debian.pp, manifests/profile/client.pp
No idea if this is going to work but I'll let you guys insult my puppet skills :)
=> st2client packages are called 'st2client' in bintray

manifests/package/install.pp, manifests/profile/client.pp, metadata.json
For now I am just fixing debian st2client. I'll do a fix when needed for RHEL.
=> Fix st2client version for bintray debian packages

templates/etc/init.d/mistral-api.erb, templates/etc/init.d/mistral.erb
As @DoriftoShoes  requeseted, it follow st2api pattern.
While with it, fix the dependency to bring mistral-api up/down with mistral (dropped off my prev commit).
=> Rewrite mistral upstart for system-v

manifests/package/debian.pp, metadata.json
The current default on the repo_base case statement wouldn't work with dl-staging201...which makes staging break.  When staging breaks, I get sad.  When I get sad, I cry tears.  Unlike Bing Bong my tears aren't candy so it isn't pleasant.
=> Lets support dl-staging201

CHANGELOG.md, manifests/params.pp, metadata.json
The service is part of st2refactor package.
=> Fix garbagecollector bug

README.md
Sync supported platforms in README with `metadata.json`.
=> Sync-up supported platforms in README

README.md
A minor cosmetic change: let's add some Puppet Forge badges.
=> Add some Puppet Forge badges

metadata.json
Fixes https://github.com/StackStorm/puppet-st2/pull/119
=> Upgrade ghoneycutt-facter to >= 3.0.0

CHANGELOG.md, manifests/user.pp
…hen the group does not already exist
=> Ensure user group exists

CHANGELOG.md, README.md
* Added puppetmodule.info badge
* Removed puppet 3 references from readme
=> Readme Update

CHANGELOG.md, manifests/profile/server.pp, metadata.json
After merge, will deploy new version.
=> Bumping release to 1.2.0

.gitattributes, .rubocop.yml, CHANGELOG.md, Gemfile, Rakefile, metadata.json, spec/default_facts.yml, spec/spec_helper.rb
=> Release 1.3.0

CHANGELOG.md, README.md
Closes #283 
Reorganize the README.md to conform to the Puppet Module README template: https://puppet.com/docs/puppet/latest/modules_documentation.html#concept-3315
=> Reorganize README.md to conform to the Puppet Module README template

.kitchen.yml, .travis.yml, CHANGELOG.md, README.md, Vagrantfile, build/ubuntu18-puppet5/Dockerfile.kitchen, build/ubuntu18-puppet5/Puppetfile, build/ubuntu18-puppet6/Dockerfile.kitchen, build/ubuntu18-puppet6/Puppetfile, manifests/init.pp, manifests/params.pp, manifests/profile/mistral.pp, manifests/profile/mongodb.pp, manifests/profile/postgresql.pp, metadata.json, spec/defines/pack_spec.rb, spec/functions/version_ge_spec.rb, test/integration/stackstorm/inspec.yml
This PR adds support for Ubuntu 18.04 and drops support for Ubuntu 14.04
**TODO**
=> Ubuntu 18.04

LICENSE
This is the final piece needed for the Approved Module development, just added the Apache 2.0 license file to the repo.
=> Added Apache license file

CHANGELOG.md, README.md
Shows off our Approved status on our README :)
=> Added Puppet Forge Endorsement badge

CHANGELOG.md, README.md, metadata.json
=> Release v1.7.0

manifests/profile/mongodb.pp
This fixes a regression caused by: https://github.com/StackStorm/puppet-st2/pull/305
I accidentally removed the full `if` condition that guarded the mongodb auth initialization by a fact.
This shouldn't have been removed, my mistake! Luckily this was caught before we did a release!
=> Fix bug where mongo auth was not guarded by a fact

.github/workflows/build.yaml
Closes https://github.com/StackStorm/puppet-st2/issues/346
=> send failed workflow notification to slack for master branch builds
