manifests/init.pp
manifests/profile/web.pp
templates/opt/st2web/config.js.erb

__Resolution__
This commit allows Angular to specify the remote st2_api URL if necessary.  The previous behavior guessed the endpoint using the host's ip address which does not apply for most cases.
__QA__
- Validated that st2workroom correctly interpolate the st2_api_url into /opt/stackstorm/static/webui/config.js when specified in Hiera.
```
st2workroom/hieradata/common.yaml
st2::st2_api_url: "http://localhost:9101"
```
- Validated that st2workroom correctly does not interpolate the st2_api_url when specified in Hiera.
```
st2workroom/hieradata/common.yaml
#st2::st2_api_url: "http://localhost:9101"
```
- Validated that Angular webapp works without the 'url' config being set and just uses the request url host.
```
vagrant@st2express:/opt/stackstorm/static/webui$ cat config.js
'use …
```

Adding st2_api_url as a hiera databound variable 

---

lib/puppet/parser/functions/st2_current_revision.rb
manifests/init.pp
manifests/package/debian.pp
manifests/package/install.pp
manifests/package/redhat.pp
manifests/params.pp
manifests/profile/client.pp
manifests/profile/server.pp
metadata.json

This PR updates the module to use APT and RPM repositories to retrieve packages over `wget` fetching. Moving between versions (major or revisions) now only requires a change to the `st2::version` parameter of the main class or in hiera.
Also bumps default version to latest stable, 0.8.3 for new users.

Convert to APT/RPM repositories

---

manifests/pack.pp
manifests/profile/server.pp
metadata.json

On first boot, st2 takes a moment to initialize, and if you hit
a pack installation command at the wrong time, you are liable
to run into something like this:
```
/Stage[main]/St2::Packs/St2::Pack[hubot]/Exec[install-st2-pack-hubot]/returns:
ERROR: HTTPConnectionPool(host='localhost', port=9101): Max retries exceeded
with url: /v1/actions/packs.install (Caused by <class 'socket.error'>:
[Errno 111] Connection refused)
```
This commit purposely introduces retries into pack installation with
a 10 second back-off time period in order to allow successful convergence
on the first pass.

Add retries to pack installation

---

manifests/package/install.pp
manifests/profile/client.pp
metadata.json

While working out some flow in our automated build, the version number for `st2client` needs to be temporarily modified to allow downloads of 0.9.0.

Update Debian `st2client` package number

---

manifests/profile/dependencies.pp
manifests/profile/python.pp

This PR introduces the StackStorm profile `st2::profile::dependencies`. This is designed as a catchall infrastructure requirement bucket, used to build docker containers.

Dependencies Profile

---

manifests/auth/mongodb.pp
manifests/auth/proxy.pp
manifests/auth/standalone.pp
manifests/auth_user.pp
manifests/init.pp
manifests/notices.pp
manifests/pack.pp
manifests/profile/client.pp
manifests/profile/fullinstall.pp
manifests/profile/server.pp
metadata.json

This PR adds authentication setup to the puppet module. Changes in this module include:
* Default `standalone` backend. In `st2::profile::fullinstall`, `standalone` file backend is setup.
* Modules for `file_based`, `mongodb`, and `proxy` authentication methods.
Once authentication is enabled, then the CLI stops working until https://github.com/StackStorm/st2/pull/1444 has been merged into `0.9.x` and made available.

ST2 Authentication

---

manifests/init.pp
metadata.json

This PR updates the default version of the Puppet module to 0.11.1

Bump default version to 0.11.1

---

manifests/pack.pp
metadata.json

This PR addresses #21 and #22, and adds several new parameters to the `st2::pack` pack deployment resource. Namely:
* `subtree` - allow control of pack deploys stored within the packs directory of a repo or at TLD.
* `register` - all the ability to register selective parts of a pack, or all.
/cc https://github.com/StackStorm/st2/issues/1616

Updates and improvements

---

files/etc/st2/st2.conf.erb

Since we don't parse out any sections and have single conf file better not remove the section. Moreover st2api uses `[auth].enable`.
The corresponding changes in workroom are probably needed to take place...

auth section fixes

---

lib/puppet/parser/functions/st2_current_revision.rb
lib/puppet/parser/functions/st2_latest_stable.rb
lib/puppet/parser/functions/st2_latest_unstable.rb
manifests/init.pp

This PR adds the ability for the Puppet Module to stay up-to-date with latest stable by default. User can lock to a specific version with Hiera, otherwise tracks upstream latest.
Please ignore my horrible string manipulation. If `nokogiri` were available, this would be much cleaner. Alas.

enable auto-updates of stable version

---

lib/puppet/parser/functions/st2_current_revision.rb

Having `OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE` here is going to disable all certificate verification inside puppet, which is suboptimal. `download.stackstorm.net` seems to have a valid certificate anyway, so this probably isn't fixing anything.

Don't disable SSL certificate verification

---

files/etc/init/st2actionrunner.conf
files/etc/init/st2api.conf
files/etc/init/st2auth.conf
files/etc/init/st2notifier.conf
files/etc/init/st2resultstracker.conf
files/etc/init/st2rulesengine.conf
files/etc/init/st2sensorcontainer.conf
manifests/init.pp
manifests/pack.pp
manifests/profile/server.pp

This PR introduces init scripts for StackStorm services. This is a temporary fix, as work is underway to properly package and distribute init scripts with our core packages. This PR grabs and modifies the init scripts as an intermediate step and gets them installed. Only supports Ubuntu/Upstart for right now.
/cc @dennybaa https://github.com/StackStorm/st2/pull/1718

Upstart init scripts

---

manifests/profile/server.pp

This PR allows adjustment of the IP and Port combinations for both the `st2api` and `st2auth` subsystems. Useful when setting up reverse proxies or locking down in other ways.

st2api/st2auth IP/Port attribute configuration

---

files/etc/init/st2actionrunner.conf
manifests/helper/actionrunner_upstart.pp
manifests/init.pp
manifests/profile/server.pp
templates/etc/init/st2actionrunner-worker.conf.erb

This PR fixes a few issues with the init scripts:
* Adds unique upstart scripts for each actionrunner, vs attempting to let upstart manage many workers
* Add `st2web` init script, properly adheres to `ST2_DISABLE_HTTPSERVER` flag, just like `st2ctl`.
This allows `st2ctl` to work 100% with the `ng_init` flag set.

Upstart init script Fixes

---

README.md
files/etc/init/st2api.conf
files/etc/init/st2auth.conf
files/etc/init/st2web.conf

This PR adds environment flags to network services when using new-style init scripts.
This is necessary to allow the Puppet module to still apply init scripts to the system, allowing `st2ctl` to continue to work until refactored to better control each service independently.
In doing this, the init script is still created, allowing us to create an anchor for other services to watch (a la https://github.com/StackStorm/puppet-st2/pull/31/files#diff-90721a90821a0f1b7129de28e6801b41R7)

Add environment flags for network services

---

files/etc/st2/st2.conf.erb

* The webhook endpoints are no longer independent but rolled into st2api.
* added `mask_secrets` properties. Default to `True`.

Update st2.conf.erb to include some new properties and drop old ones.

---

manifests/init.pp
manifests/profile/mistral.pp
metadata.json

This PR adds the ability to manage Mistral service, and change the configuration for Mistral to point to alternate endpoints to communicate with the backend.
This is essential to allow management of the service via a WSGI server or other mechanism.

Mistral Service Management

---

manifests/kv.pp
manifests/kvs.pp
manifests/profile/fullinstall.pp
metadata.json

This PR creates a model that allows users to set StackStorm K/V pairs via Puppet. Useful for setting permanent state.

Manipulate K/V Store

---

manifests/init.pp
manifests/profile/client.pp
manifests/profile/mistral.pp
manifests/profile/server.pp
manifests/profile/web.pp

This PR updates the puppet module to enable auto-updates for StackStorm, and disallow updates when offline. These flags will be used to setup offline VMDK/AMI.
The downside to this is now the default behavior is to increment the StackStorm version on release for this repository, but this should not be a huge issue.

Toggle Autoupdate

---

lib/puppet/parser/functions/st2_latest_stable.rb

* The original sort looks ok but it acts very strange on the minor and patch values
* The new sort is not as elegant but it works reliably.
With the previous sort even with ["0.11.0", "0.11.1", "0.11.2", "0.11.2", "0.11.3", "0.11.4", "0.11.5", "0.11.6", "0.12.0", "0.12.1", "0.12.2", "0.8.3", "0.9.0", "0.9.0", "0.9.1", "0.9.2"]
it would return 0.12.1 as highest. The new one does the right sort.

Original sort was broken so fixed with a somewhat stabler sort

---

manifests/profile/mistral.pp
metadata.json

This PR updates the mistral profile to use random string passwords, not random number passwords.

FQDN String for Mistral

---

manifests/init.pp
manifests/profile/client.pp
manifests/profile/mistral.pp
manifests/profile/server.pp

This PR modifies the `client`, `server`, and `mistral` profiles for StackStorm to pull branches/dependencies from the appropriately tagged commit for a given version.
/cc @manasdk @m4dcoder

Align git tag of repositories to version

---

CHANGELOG.md
manifests/init.pp
metadata.json

This PR bumps the default version of StackStorm to `0.13.1` after yesterday's release.

Bump default version to 0.13.1

---

CHANGELOG.md
manifests/stanley.pp
metadata.json

Via the `st2installer`, user will provide a value they want for their `stanley` user, essentially the SSH account that will be used to execute commands around a computing environment.
`st2installer` passes in `st2::stanley::username`, which is promptly ignored today. This changes that.

Stanley User Adjustment

---

CHANGELOG.md
manifests/profile/server.pp
metadata.json

This PR updates the path to the logger config for `st2auth`. Found while trying to debug why st2api and st2auth logs are empty in st2workroom.

fix path for st2auth logger config

---

CHANGELOG.md
manifests/pack.pp

In the past, the `st2::pack` resource would try and restart StackStorm as part of a pack installation. However, StackStorm pack installation no longer needs a helping hand, and can handle restarting of components on its own.

Stop restarting StackStorm

---

manifests/init.pp
manifests/profile/client.pp
metadata.json
templates/etc/profile.d/st2.sh.erb

This PR updates StackStorm to add an option to the `st2::profile::client` class to optionally enable global environment variables for StackStorm. This is good for the AIO installer or other nodes where we're doing a bunch of pre-config for users.
Also a good way to standardize clients across a fleet.

Environment Variables

---

manifests/init.pp
metadata.json

This PR updates the module to use StackStorm 0.13.2 as the default release.

bumping to StackStorm v0.13.2

---

CHANGELOG.md
manifests/client/settings.pp
manifests/profile/client.pp

This PR abstracts the config settings defined previously in
::st2::profile::client into a new defined type, ::st2::client::settings,
that can be used to generate CLI configuration for any user.

abstract st2::client::settings to defined type

---

CHANGELOG.md
manifests/profile/client.pp
manifests/profile/server.pp

This commit moves all associated resources for processing
requirements.txt into the same conditional block that toggles
on and off the download based autoupdate being true or false.
Keeping the resources together repairs a condition where catalog
compilation would fail due to `autocomplete` being `false`

Move python-requirements into resource fence

---

CHANGELOG.md
manifests/profile/mistral.pp
metadata.json

This PR updates the Mistral profile to automatically restart the Mistral service anytime the mistral config is changed.
This allows service subsystem changes on the fly.

refresh mistral service on update

---

CHANGELOG.md
manifests/rbac.pp
metadata.json
templates/rbac/assignments/user.yaml.erb

This PR adds a defined type (`st2::rbac`) to manage RBAC roles on a StackStorm system.

RBAC Management Defined Type

---

CHANGELOG.md
manifests/init.pp
manifests/profile/server.pp
metadata.json

This PR adds the ability for a user to specify where on the filesystem the SSH key is for remote runners.

add ability to adjust SSH key location

---

CHANGELOG.md
manifests/profile/mistral.pp
metadata.json

This PR ensures that PostgreSQL stuffs is done before Mistral services are started/reloaded.

Start Postgresql before Mistral

---

manifests/helper/service_manager.pp
manifests/params.pp

This PR updates the package map to include packages regardless how they are referenced, and a less restrictive resource ordering with Spaceships! :alien:

Repair mappings for Packages on RHEL 7

---

CHANGELOG.md
manifests/auth/mongodb.pp
manifests/auth/proxy.pp
manifests/auth/standalone.pp
manifests/helper/auth_manager.pp
manifests/profile/mistral.pp
manifests/profile/server.pp
metadata.json

This PR updates the service refresh to look for `Ini_setting` resources that have been tagged with `st2::config`. Allows loose coupling of service restart in classes outside of the module. (for example, RBAC)

restart services when edits are made

---

CHANGELOG.md
manifests/package/install.pp
metadata.json

Even though the build pipeline uses the same workflow and same instructions and same scripts as RHEL 7 and friends, a small shift of a period (`.`) happens in the version name.
This PR corrects this behavior if it is observed on RHEL 6

Hotfix for RHEL 6 Client Package

---

CHANGELOG.md
manifests/init.pp
manifests/profile/server.pp
metadata.json

While testing, `st2ctl` needs this flag to ensure that we're using actual services, not stand-alone apps.
Needed until upstream packages fully merge.

Re-enable NG_INIT until upstream merge

---

CHANGELOG.md
files/etc/init.d/st2actionrunner
files/etc/init.d/st2api
files/etc/init.d/st2auth
files/etc/init.d/st2notifier
files/etc/init.d/st2rulesengine
files/etc/init.d/st2sensorcontainer
files/etc/init.d/st2web
metadata.json

This PR ensures that sysv actionrunner scripts do not output to STDOUT/STDERR
Also ensures that `/etc/environment` is sourced.

sysv init script fixes

---

CHANGELOG.md
manifests/helper/auth_manager.pp
metadata.json

This PR updates the `Class['::st2::helper::auth_manager']` to accept a `backend_kwargs` argument as a hash to be used for configuration of an authentication plugin.

enable backend kwargs for auth manager

---

CHANGELOG.md
manifests/helper/auth_manager.pp
metadata.json

This PR fixes an import error seen when attempting to use the `backend_kwargs` attribute by properly importing libraries the ruby way.

Fix import error for JSON rendering in auth_manager

---

CHANGELOG.md
manifests/helper/auth_manager.pp
manifests/params.pp
manifests/user.pp
metadata.json

This PR removes the static robot user for the `st2robots` group. Not a super great assumption to set UID... this can be managed by the user as needed.

remove GID for st2robots user

---

CHANGELOG.md
manifests/profile/server.pp
metadata.json

An external API url setting is needed to configure api_url in the auth section of st2.conf

Api url setting

---

CHANGELOG.md
manifests/helper/auth_manager.pp
manifests/profile/server.pp
metadata.json

This PR updates the puppet module to limit the management of the `api_url` to only the auth_manager helper.

stop managing api_url in st2::Profile::server

---

CHANGELOG.md
manifests/params.pp
manifests/stanley.pp
manifests/user.pp
metadata.json

This PR ensures that the `st2pack` exists (created by packages), and that the default system user is included in this group.

adding default st2pack group to install

---

CHANGELOG.md
manifests/pack.pp
metadata.json

This PR ensures that the puppet module correctly sets permissions on the Pack directory to allow services (`st2api`) to read these files when run under a WSGI daemon.

Ensure pack directory

---

manifests/helper/service_manager.pp
manifests/params.pp
manifests/profile/server.pp
templates/etc/systemd/system/st2actionrunner.service.erb

Debian Jessie Support

---

CHANGELOG.md
files/etc/init/st2api.conf
files/etc/init/st2auth.conf
files/etc/init/st2notifier.conf
files/etc/init/st2resultstracker.conf
files/etc/init/st2rulesengine.conf
files/etc/init/st2sensorcontainer.conf
files/etc/init/st2web.conf
templates/etc/init/st2actionrunner-worker.conf.erb

This fixes #120.
I've tested it on build server and it seems to work fine.
For reference, see http://upstart.ubuntu.com/cookbook/#console (and upstart which runs on Ubuntu 12.04 is 1.12.1-0ubuntu4.2 so `console log` is the default).
P.S. 1 We should also include this fix in v1.1.1.
P.S. 2 That was the root cause of st2build002 and st2ops constantly getting "messed" up (it was disk being full) - it started happening after we upgraded st2 to a newer version which ships with and uses upstart scripts.

Disable upstart logging for st2 services

---

CHANGELOG.md
manifests/init.pp
manifests/package/debian.pp
manifests/params.pp
metadata.json

This PR updates the module to allow for using/testing out the new BinTray repositories currently being tested.
To use:
```
st2::repo_root: https://dl.bintray.com
st2::repo_env: staging
```
```
class { '::st2':
repo_root => 'https://dl.bintray.com',
repo_env  => 'staging',
}
```

Add support for bintray debian

---

CHANGELOG.md
manifests/profile/web.pp
metadata.json

In this PR, `st2web` can run into a situation where `autoupdate` is set to `false` (Default), and the bootstrap of the class is done.
This adjusts the metaparameter ordering to keep the DAG intact, but move the resource dependency inside of the conditional to avoid compilation errors.

Move misaligned resource metaparameter inside conditional

---

spec/classes/st2_package_debian_spec.rb

https://download.stackstorm.com/deb/ -> https://downloads.stackstorm.net/deb/
Seems there is no such working url: https://download.stackstorm.com/deb/
Related to https://github.com/StackStorm/puppet-st2/pull/130 change

Fix StackStorm download URL for deb packages

---

spec/classes/st2_package_debian_spec.rb

See: https://github.com/StackStorm/puppet-st2/pull/130#issuecomment-165111196
```sh
$ apt-key finger
....
pub   4096R/D401AB61 2015-02-17
Key fingerprint = 8756 C4F7 65C9 AC3C B6B8  5D62 379C E192 D401 AB61
uid                  Bintray (by JFrog) <bintray@bintray.com>
sub   4096R/DBE1D0A2 2015-02-17
```
https://bintray.com/docs/usermanual/uploads/uploads_gpgsigning.html
Please double-verify before merging this! 
```sh
$ wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -
$ add-apt-repository 'deb https://dl.bintray.com/stackstorm/trusty_staging unstable main'
$ apt-get update
$ apt-get install st2api
$ apt-key finger
```

Fix Bintray GPG key fingerprint

---

manifests/init.pp
manifests/profile/mistral.pp
metadata.json
templates/etc/init.d/mistral-api.erb
templates/etc/init/mistral-api.conf.erb
templates/etc/init/mistral.conf.erb
templates/etc/systemd/system/mistral-api.service.erb
templates/etc/systemd/system/mistral.service.erb

Move mistral api under gunicorn

---

manifests/profile/mistral.pp

Refactor the use of syncdb script to mistral-db-manage command to create and populate the mistral database. The mistral-db-manage also adds appropriate version information to the database. This is required for DB upgrade when moving to the next mistral version.

Refactor mistral DB setup to use mistral-db-manage

---

files/etc/init.d/st2actionrunner
metadata.json

This is my second attempt at this PR since apparently the first one was smarter than me.
Currently `service st2actionrunner stop` doesn't stop all services on systems using the SysV script. This fixes that because awesome fix is awesome.

Initd actionrunner fix

---

CHANGELOG.md
manifests/stanley.pp
manifests/user.pp
metadata.json

This also changes the behavior of the `st2::user` class and makes `ssh_public_key` and `ssh_private_key` variables optional even if `client` / `server` variable is set to true.
Instead of aborting and failing if no key is provided, we now simply don't install any key if one is not explicitly provided.
This results in a much safer default behavior.
When this PR is reviewed and +1'ed, it needs to be merged, new version of module pushed to puppet worked and we need to create a testing branch which uses this new version in st2workroom.
TODO:

Don't install a default public and private key for stanley user if no key is provided

---

manifests/package/debian.pp
metadata.json

I added a secondary http to the beginning of the protocol for some unexplainable reason last night.  This fixes that.

Remove duplicate http protocol from repo urls

---

files/etc/st2/st2.conf.erb
metadata.json

See https://stackstorm.atlassian.net/browse/STORM-1961 for details.

RFR: Set virtualenv_opts to just --system-site-packages for old packages

---

files/etc/st2/st2.conf.erb
metadata.json

Reverts StackStorm/puppet-st2#148
The workroom tests are still failing. The config never made it to the boxes. I have no idea what's wrong. At this point, I'll revert this change and also the st2 change https://github.com/StackStorm/st2/pull/2372.
Unless this puppet change lands correctly, we cannot do anything.

Revert "RFR: Set virtualenv_opts to just --system-site-packages for old packages"

---

files/etc/init.d/st2garbagecollector
files/etc/init/st2garbagecollector.conf
metadata.json

This is needed so this change won't break existing 1.2.0 installations.

Update init scripts to exit if gargabe collector service is not available

---

manifests/profile/client.pp
manifests/profile/mistral.pp
manifests/profile/server.pp
manifests/profile/web.pp

Map false to false in case fact is there and it has a value of false

---

manifests/package/debian.pp

fixes the following depreciation warnings:
```
Warning: Scope(Apt::Source[stackstorm]): $include_src is deprecated and will be removed in the next major release, please use $include => { 'src' => false } instead
Warning: Scope(Apt::Source[stackstorm]): $key_source is deprecated and will be removed in the next major release, please use $key => { 'source' => https://downloads.stackstorm.net/deb//pubkey.gpg } instead.
Warning: Scope(Apt::Key[Add key: 1E26DCC8B9D4E6FCB65CC22E40A96AE06B8C7982 from Apt::Source stackstorm]): $key_source is deprecated and will be removed in the next major release. Please use $source instead.
```

Fix depreciation warnings with puppetlabs-apt resources

---

manifests/profile/mistral.pp
manifests/profile/source.pp
metadata.json

The first commit fixes the fact that the module never makes sure that git is installed before it tries to clone git repos.  It appears that the maestrodev-git module was included as a dependency for this, but it was not actually being used to achieve that goal.  That said, because puppetlabs-stdlib is already included, this behavior can be achieved without the extra module dependency using ensure_packages instead.
And in the habit of leaving something better than you found it, I also cleaned up a bunch of puppet-lint issues with the mistral.pp file (one of the two that I modified).  This does not fix all of them, but it does fix the vast majority.

Require git

---

manifests/profile/python.pp

Currently on a "clean" container, stackstorm fails to install when using the latest pip that ships with 14.04 (which is the "supported platform" according to stackstorm's docs).  Ensuring that the latest pip is installed from pypi fixes this.
Additionally, This uses latest/present/absent rather than true/false to fix a few depreciation warnings.
There are also some puppet-lint fixes in there as well.
This PR supersedes PR #118 which does not have the fix for the depreciation warnings.

Fix depreciation warnings and install latest pip from pip

---

.travis.yml

Add Slack notifications per https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications
This will post build failures to `#puppet` channel in `stackstorm-community` Slack.
Another change: enable [TravisCI cron builds](https://docs.travis-ci.com/user/cron-jobs/) (daily builds triggered for `master`).
This way we'll get notification if something is broken (usually a sign of `st2` breaking change or regression).

Add Slack notifications on CI failures

---

manifests/init.pp
manifests/params.pp
manifests/profile/mongodb.pp

The new parameter value will be passed to module 'mongodb'.
Add missing parameter $st2::params::mongodb_admin_username
Fix a typo in mongodb parameter '$mongdb_version'

Add new parameter 'mongodb_manage_repo'

---

CHANGELOG.md

I've missed requiring PR submitters to update the CHANGELOG on a few recent PRs.
I've cleaned this up in this PR and will be sure to require CHANGELOG updates where appropriate in the future.

Updated CHANGELOG to reflect recent PRs.

---

CHANGELOG.md
README.md
manifests/init.pp
manifests/params.pp
manifests/profile/chatops.pp
manifests/profile/fullinstall.pp
templates/st2chatops.env.erb

- Install needed packages
- Manage st2chatops.env file (hubot and adapter configuration)
- Install optional nodejs modules for hubot adapter
- Manage st2chatops service
Example hiera config for setting up hubot and rocketchat adapter:
```
st2::chatops_npm_packages:
hubot-adapter:
package: 'hubot-rocketchat'
source: 'git+ssh://git@git.company.com:npm/hubot-rocketchat#master'
st2::chatops_adapter_config:
HUBOT_ADAPTER: rocketchat
ROCKETCHAT_URL: "https://test-chat.company.com:443"
ROCKETCHAT_ROOM: 'sandbox'
LISTEN_ON_ALL_PUBLIC: true
ROCKETCHAT_USER: st2
ROCKETCHAT_PASSWORD: xxxxxx
ROCKETCHAT_AUTH: password
RESPOND_TO_DM: true
```
I am successfully using this in my test env so it passes my use cases. Any comments are appreciated.

 Install and manage st2chatops

---

CHANGELOG.md
lib/puppet/provider/st2_pack/default.rb
lib/puppet/type/st2_pack.rb
manifests/init.pp
manifests/pack.pp
manifests/packs.pp
manifests/profile/fullinstall.pp
manifests/profile/server.pp
spec/defines/pack_spec.rb

Refactor st2 package installation to use new pack install commands.
- New parameters 'packs' in class '::st2' containing hash of st2 pack names and their configurations.
- New parameter 'index_url' in class '::st2' for providing optional st2 Exchange index file location (in case no internet connection)
- New type and provider st2_pack
- Refactor pack.pp to use st2_pack type
- Move control commands to ::st2 as there they can be used as a common sync points by all classes.
- Do not force installation of package 'st2'
I am successfully using this in my test env to install new packs from my internal git server. I have not tried to install any packages from the actual st2 Exchange. These changes should not break backward compatibility (existing ::st2::packs hiera configs should be ok). I am …

New type and provider for installing packs.

---

CHANGELOG.md
manifests/init.pp
manifests/profile/chatops.pp
manifests/profile/mistral.pp
manifests/profile/mongodb.pp
manifests/profile/nodejs.pp
manifests/profile/server.pp
manifests/profile/web.pp
metadata.json

Closes #170, closes #177
This upgrades the puppet module to install MongoDB 3.4 (#170) and NodeJS 6.x (#177) if installing StackStorm >= 2.4.0

Upgrade to MongoDB 3.4 and NodeJS 6.x

---

CHANGELOG.md
docs/Puppetfile
manifests/profile/nodejs.pp
metadata.json

Updated our metadata.json to the new voxpupuli repo for both rabbitmq and mongodb, closes #186 .
Also fixed a bug in mongodb profile that i introduced accidentally in my last PR.

Migrate to voxpupuli/rabbitmq module

---

.fixtures.rhel6.yml

puppetlabs/inifile module dropped support for Ruby < 2.0 and Puppet 3.x in a release earlier this week.
This change locks the module to an old version that is compatible with our legacy RHEL 6 build.

Lock puppetlabs/inifile for RHEL6 builds

---

CHANGELOG.md
manifests/params.pp

In the latest version of MongoDB module they enforced the `port` must be an integer, we had it set to a string causing a build failure in Puppet 4 & 5.
This simply changes our value for the MongoDB port to an integer in `::st2::params`

Set MongoDB port to integer

---

build/centos7/Gemfile
build/centos7/Gemfile.lock

We've had a couple of random build failures for CentOS 7 in `cron` due to Bundler resolving gems in a weird way. In public_suffix `3.0.0+` Ruby 2.1+ is required, that was breaking the build. This locks the `public_suffix` gem for the CentOS 7 build to the `~> 2.0.0` meaning `< 3.0.0`.

Locked the public_suffix gem for CentOS7 build using ruby 2.0

---

build/centos6/Puppetfile
build/centos7/Puppetfile
build/ubuntu14/Puppetfile
build/ubuntu16/Puppetfile

Latest version of the saz/sudo module dropped support for Puppet 3.x. This PR locks the version of that module to the latest puppet 3 supported version for our puppet 3 builds.

Locked version of saz/sudo module

---

manifests/pack.pp

Previously it was setup so that the `/opt/stackstorm/packs` directory required the `st2` package to be installed.
This dependency is not necessary and can cause issues in certain scenarios.

Fixed false dependency on st2 package

---

CHANGELOG.md
README.md
docs/TODO.md
manifests/auth/keystone.pp
manifests/auth/ldap.pp
manifests/auth/mongodb.pp
manifests/init.pp
manifests/profile/client.pp
manifests/profile/mongodb.pp
manifests/profile/nodejs.pp
manifests/profile/python.pp
manifests/profile/server.pp
manifests/profile/web.pp

Previously, by default, this module was configured to auto-updated all of the packages that this module manages.
That means when 2.7 came out, it auto-updated everything in our environment (not good).
This changes the behavior to install the latest version available during initial install (`yum -y install st2`), and subsequent runs just ensure the package is installed. Updates can then be managed out-of-band by organizations at their leisure.

Stop Puppet from auto-updating 

---

CHANGELOG.md
manifests/params.pp
manifests/profile/server.pp

Added service definition for `st2workflowengine` but only if we're installing a version >= 2.8.0

Adding st2workflow engine

---

manifests/profile/nodejs.pp

Current CentOS 7 build is failing due to GPG key for EPEL not being setup properly prior to NodeJS install.
Not sure WHY this is not working since we have ordering defined correctly. This PR is experimenting to try and fix the problem.

Fixing CentOS 7 NodeJS issue

---

CHANGELOG.md
README.md

Puppet 3 is EOL. 
This adds a notice for the intention of dropping Puppet 3 support in the next minor release.

Deprecation warning for Puppet 3

---

CHANGELOG.md
build/puppet4/Puppetfile
build/puppet5/Puppetfile

Someone release a new module with different dependencies.
This fixes them by reordering puppetfile for puppet4 + 5

Fix build for puppet4/5

---

.kitchen.yml
.travis.yml
CHANGELOG.md
build/centos6-puppet4/Dockerfile.kitchen
build/centos6-puppet5/Dockerfile.kitchen
build/centos6-puppet6/Dockerfile.kitchen
build/centos6-puppet6/Puppetfile
build/centos7-puppet5/Dockerfile
build/centos7-puppet5/Dockerfile.kitchen
build/centos7-puppet6/Dockerfile
build/centos7-puppet6/Dockerfile.kitchen
build/centos7-puppet6/Puppetfile
build/ubuntu14-puppet6/Dockerfile.kitchen
build/ubuntu14-puppet6/Puppetfile
build/ubuntu16-puppet6/Dockerfile.kitchen
build/ubuntu16-puppet6/Puppetfile
metadata.json

Closes #243 
Puppet 6 was just released. This adds unit tests and integration tests for all platforms. It also bumps the supported puppet version upper limit in `metadata.json` from `< 6.0` to `< 7.0`.
This also fixes the build error on `master` last night. Puppet, when releasing 6, changed the URL of the RPM repo packages for 5.

Add support for Puppet 6

---

.travis.yml
CHANGELOG.md
build/centos7-puppet4/Dockerfile

Fixed build for Puppet 4. New version of rubygem-update requires Ruby 2.3.0 and Puppet 4 requires 2.1.x. When running `gem update --system` this updated the gem past the installed ruby version, breaking the build. Instead, we simply leave the system gems alone during the build.

Fix Puppet 4 build

---

CHANGELOG.md
README.md

Simple documentation change for now.
The next minor release we'll adjust the Travis text matrix.
The next major release we'll raise the minimum Puppet version in `metadata.json`.

Deprecated Puppet 4

---

CHANGELOG.md
build/centos6-puppet4/Puppetfile
build/centos6-puppet5/Puppetfile
build/centos6-puppet6/Puppetfile
build/centos7-puppet4/Puppetfile
build/centos7-puppet5/Puppetfile
build/centos7-puppet6/Puppetfile
build/ubuntu14-puppet4/Puppetfile
build/ubuntu14-puppet5/Puppetfile
build/ubuntu14-puppet6/Puppetfile
build/ubuntu16-puppet4/Puppetfile
build/ubuntu16-puppet5/Puppetfile
build/ubuntu16-puppet6/Puppetfile
metadata.json

Fixed build for new release of `puppet/nginx` causing conflict with `puppetlabs/stdlib`.
The new version `0.16.0` of `puppet/nginx` requires `puppetlabs/stdlib >= 5.0.0`.
Several other modules we depend on require `puppetlabs/stdlib < 5.0.0` causing a conflict.
To fix this, we've pinned `puppet/nginx` to `0.15.0` in the Puppetfiles used
for testing.

Fixing build caused by new puppet/nginx release

---

CHANGELOG.md
lib/puppet/provider/st2_pack/default.rb
spec/unit/puppet/provider/st2_pack/default_spec.rb

Previously when the `st2_pack` resource was trying to run and invalid credentials were passed, then the `st2 auth` command would silently fail, then a bad "token" string would be passed to the `st2 pack install` command resulting in odd errors.
This PR fixes this issue by passing in all necessary options in order to actually fail the command if the `exit status != 0`.

Fixed bug where auth failure reason was not logged to the user

---

CHANGELOG.md
lib/puppet/provider/st2_pack/default.rb
spec/unit/puppet/provider/st2_pack/default_spec.rb

We use "st2 pack list" command to list currently installed packages. We
should compare the configured pack names with names in the column "ref", not with the names in the
column "name".

Use column "ref" when checking already installed packs.

---

CHANGELOG.md
manifests/profile/mistral.pp
metadata.json

Two things:
1. 1.5.0 release (about time)
2. Fixed a bug in the Mistral connection string parameter. Previously we were just writing the user-inputted password. This would have been fine except that the Mistral connection is a URL, so if passwords contained special characters, then the URL could be invalid. Simple URL escape on the password and we're all good.

1.5.0 release. Fixed bug in Mistral connection string

---

build/kitchen/Gemfile

Recent build problems have been caused by a bug in the `train` gem on versions `> 3.2.0`: https://github.com/inspec/train/issues/548
This PR pins the `train` gem to `3.2.0` before the bug was introduced, causing `sudo` syntax errors when doing `inspec` verify.

Reverting to old version of train gem to fix build problems

---

CHANGELOG.md
build/centos6-puppet5/Puppetfile
build/centos6-puppet6/Puppetfile
build/centos7-puppet5/Puppetfile
build/centos7-puppet6/Puppetfile
build/ubuntu14-puppet5/Puppetfile
build/ubuntu14-puppet6/Puppetfile
build/ubuntu16-puppet5/Puppetfile
build/ubuntu16-puppet6/Puppetfile
metadata.json

Closes #282 
In order for us to received the "Approved" status for a Puppet module we need to fix up some of our dependencies in `metadata.json`.
- Do not have any "open ended" dependencies, ie we need to define an upper bound.
- Do not have any unused dependencies.

Fixing puppet module dependencies

---

.travis.yml
CHANGELOG.md
tasks/key_decrypt.py
tasks/key_get.py
test/unit/test_tasks_key_get.py

Ran into two bugs:
1) `st2::key_decrypt` had an incompatible python3 statement.
2) `st2::key_get` had a bug in its logic when trying to parse the results. It always assumed a key existed in the dictionary, but if an error occurred the output might not be JSON so we need to handle this correctly.

Fix bugs in st2::key_get and st2::key_decrypt

---

CHANGELOG.md
files/st2_task_base.py
test/unit/test_files_st2_task_helper.py

Before this fix, new versions of bolt were running the tasks and getting an output like: 
```
2020-06-23 10:37:22,090  WARNING - Locale unknown with encoding ANSI_X3.4-1968 which is not UTF-8 is used. This means that some functionality which relies on outputting unicode characters won''t work. You are encouraged to use UTF-8 locale by setting LC_ALL environment variable to en_US.UTF-8 or similar.
```
When this warning was printed from the `st2` CLI it would cause the tasks to fail parsing the JSON output.
This fix sets the `LC_ALL` locale to be UTF-8 so that this warning isn't printing allowing JSON to be parsed correctly and tasks to succeed.

Hard code locale so that st2 command is called with utf8

---

CHANGELOG.md
README.md
tasks/key_get.py
tasks/key_load.py
tasks/pack_install.py
tasks/pack_list.py
tasks/pack_register.json
tasks/pack_register.py
tasks/rule_disable.json
tasks/rule_disable.py
tasks/rule_list.json
tasks/rule_list.py
tasks/run.json
tasks/run.py
test/unit/test_tasks_key_get.py
test/unit/test_tasks_key_load.py
test/unit/test_tasks_pack_install.py
test/unit/test_tasks_pack_list.py
test/unit/test_tasks_pack_register.py
test/unit/test_tasks_rule_disable.py
test/unit/test_tasks_rule_list.py
test/unit/test_tasks_run.py

We were maintaining a few st2 tasks in a private fork for no good reason. This PR migrates those tasks to the open source version so everyone can benefit.

Add new tasks: st2::pack_register, st2::rule_disable, st2::rule_list, st2::run

---

.fixtures.yml
CHANGELOG.md
build/centos6-puppet5/Puppetfile
build/centos6-puppet6/Puppetfile
build/centos7-puppet5/Puppetfile
build/centos7-puppet6/Puppetfile
build/ubuntu14-puppet5/Puppetfile
build/ubuntu14-puppet6/Puppetfile
build/ubuntu16-puppet5/Puppetfile
build/ubuntu16-puppet6/Puppetfile
build/ubuntu18-puppet5/Puppetfile
build/ubuntu18-puppet6/Puppetfile
metadata.json

Prepping for the 1.7.0 release.
The stahnma-epel repo is deprecated and has been replaced with puppet-epel. This migrates to the new module.

Replace stahnma-epel with puppet-epel

---

.travis.yml

Closes #241 
Enables the Travis deploy feature to automatically upload modules to the forge. This is triggered by a release tag on the repo.

Enable travis to deploy the module to the forge

---

.travis.yml

- Switch travis to using bionic as its base OS
- Remove the deprecated `sudo` key (causes a warning)
- Set the `os: linux` key so we don't get a notice in Travis.

Switch travis to using bionic as its base OS

---

CHANGELOG.md
manifests/profile/server.pp

I noticed this morning that there was a new default logging config in /etc/st2/st2.conf default... although this isn't reflected in https://github.com/StackStorm/st2/blob/master/conf/st2.conf.sample.
The new logging configs for `api`, `auth` and `stream` are `/etc/st2/logging.<service>.gunicorn.conf` 
This changes reflects the new default to match one-line installer.

Correct logging config for api, auth and stream to point at gunicorn config

---

CHANGELOG.md
REFERENCE.md
manifests/init.pp
manifests/profile/web.pp

Previously we were always generating a self-signed SSL certificate for StackStorm.
Commonly users want to be able to manage their own SSL certs so they can be signed with a proper CA.
This PR adds a flag to prevent this module from generating a self-signed cert and instead expects the user to create the cert themselves.

Add new parameter st2::ssl_cert_manage so users can manage their own SSL certs

---

CHANGELOG.md
REFERENCE.md
manifests/profile/nginx.pp
manifests/repo.pp
plans/upgrade_mongodb.pp

This plan follows the MongoDB upgrade procedures and allows StackStorm 3.2 users migrating to StackStorm 3.3 to upgrade their MongoDB from 3.4 to 3.6 and ultimately to 4.0.

Added plan to upgrade MongoDB

---

CHANGELOG.md
manifests/profile/web.pp
spec/classes/profile/web_spec.rb

This change adds the 'Strict-Transport-Security' header to the nginx server statements.
It also sets the max-age timeout to 31536000 seconds (1 year) and includes subdomains.

Enable HSTS header for SSL server

---

CHANGELOG.md
manifests/auth/ldap.pp
manifests/auth/pam.pp

Previously the system dependencies for the auth packages had tags declared. These tags were not used. It caused issues with things such as `gcc` when other modules would try to declare these packages, the declarations would conflict because the `Package[gcc]` declaration in the other modules wouldn't include the StackStorm tags.
Since these tags are unused, i simply removed them!

Remove tags from system package dependencies
